# Generated by Django 2.0.5 on 2020-02-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_yunicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='icon',
        ),
    ]
